from typing import Protocol, Any, Optional

class StateRepository(Protocol):
    def get_active_project(self) -> str: ...
    def set_active_project(self, name: str) -> None: ...
    def get_language(self) -> str: ...
    def set_language(self, lang: str) -> None: ...
    def get_value(self, key: str, default: Any = None) -> Any: ...
    def set_value(self, key: str, value: Any) -> None: ...
